name: SoupLab
version: ${project.version}
main: me.jonakls.souppvp.SoupLab
authors: [ Jonakls ]
commands:
  soup:
    aliases:
      - soupvp
    description: General command
  kits:
    aliases:
      - kit
      - pvp
    description: Kit command